GET   http://localhost:4004/catalog/Users
# Content-Type:application/json

# {
# 	"Username": ilip_ST,
# 	"Password": "12345",
# 	"EmailId": "ASDF_ST@gmail.com",
# 	"ImageURL": "sdasd"
# }
### Security testing
GET   http://localhost:4004/catalog/Products

### Test locally with the Mock stratagy
GET   http://localhost:4004/catalog/ProductsInventory
Authorization: Basic VaraPrasad:
